import '../../public/css/globals.css'
import type { Metadata } from 'next'
import LocalFont from 'next/font/local'
import { getServerSession } from 'next-auth'

import SessionProvider from './components/session-provider'

const inter = LocalFont({
  src: '../../public/fonts/Inter-Variable.ttf'
})

export const metadata: Metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={`${inter.className} h-screen w-full antialiased`}>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
