import '../../public/css/globals.css'
import type { Metadata } from 'next'
import LocalFont from 'next/font/local'
import { getServerSession } from 'next-auth'

import SessionProvider from './components/session-provider'
import { TopNav, Sidebar } from '@/app/components'

const inter = LocalFont({
  src: '../../public/fonts/Inter-Variable.ttf'
})

export const metadata: Metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-screen antialiased`}>
        <SessionProvider session={session}>
          {session ? (
            <div className="w-full flex">
              <div className="hidden lg:block lg:basis-1/6">
                <div className="sticky top-0 left-0 h-screen">
                  <Sidebar />
                </div>
              </div>
              <div className="mt-10 sm:mt-0 flex-1 lg:basis-5/6">
                {children}
              </div>
              <div className="block sm:hidden">
                <TopNav />
              </div>
            </div>
          ) : (
            <div className="w-full h-screen">
              {children}
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
